<?php
session_start();
include 'db.php';

if ($_SERVER['REQUEST_METHOD'] == 'POST' && $_SESSION['role'] == 'student') {
    $submission_id = $_POST['submission_id'];  // Passed from the form or code
    $testcase_id = $_POST['testcase_id'];      // Passed from the test cases available
    $student_output = $_POST['student_output']; // Output generated by student's submission

    // Get expected output from the test case
    $stmt = $conn->prepare("SELECT expected_output FROM testcases WHERE testcase_id = ?");
    $stmt->bind_param("i", $testcase_id);
    $stmt->execute();
    $stmt->bind_result($expected_output);
    $stmt->fetch();
    $stmt->close();

    // Compare actual output with expected output
    $passed = ($student_output == $expected_output) ? 1 : 0;
    $marks = $passed ? 100 : 0;  // Assuming 100 marks for a passed test case

    // Insert result into the results table
    $stmt = $conn->prepare("INSERT INTO results (submission_id, testcase_id, actual_output, passed, marks) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("iisii", $submission_id, $testcase_id, $student_output, $passed, $marks);

    if ($stmt->execute()) {
        echo "Result recorded successfully!";
    } else {
        echo "Failed to record result.";
    }

    $stmt->close();
    $conn->close();
}
