# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9U1TxJ2UCoMZzdzluQ-0rkMw0e4957o
"""

def square_number(n):
    return n * n

if __name__ == "__main__":
    input_data = int(input())
    print(square_number(input_data))